kind: Service
apiVersion: v1
metadata:
  name: helloserver-service-wl
spec:
  selector:
    app: helloserver-wl
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30088
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-helloserver-wl
  labels:
    app: helloserver-wl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloserver-wl
  template:
    metadata:
      labels:
        app: helloserver-wl
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: helloserver
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080
